# pandoc --defaults _codebraid_preview.yml --pdf-engine weasyprint -o report.pdf
input-files:
- background.md
- planning.md
- research.md
- development.md # only a header
- dev-data.md
- dev-design.md
- dev-frontend.md
- dev-backend.md
- dev-deployment.md
- dev-testing.md
- evaluation.md
- conclusion-summary.md
- appendix.md


# page consting of an h1 header - due to pandoc not supporting an option to title the References it auto generates
- references.md


# adds preface.md before the table of contents, and removes the headings of this file from the index
include-before-body: header.html

table-of-contents: true
toc-depth: 3
#
variables:
  toc-title: "Table of Contents"


number-sections: true

# pdf-engine-opts:
#   toc:
